### ISSUE TITLE
Better error handling for errors

### ISSUE THREAD

**Issue by pythonpete32** [nation3/court#61]
![CleanShot 2022-11-09 at 20 32 09@2x](https://user-images.githubusercontent.com/50079365/200886717-2912537e-81b5-4b4e-a537-6819eefad2e1.png)

clicking button does nothing because the addresses are invalid but there is no indication thats why other than the banner, it would be better of the input fields have an error state

**Comment by xPi2** [comment]
Good feedback. There is already a task for that: https://app.dework.xyz/nation3/nation3-court-v1-p?taskId=a9f092d3-bd8a-4cb6-9259-f22a61e88fec
